In [3]:
import numpy as np
height=[20.865,21.643,22.834,25.62]
np_height=np.array(height)
np_height

array([20.865, 21.643, 22.834, 25.62 ])

In [26]:
bmi=np.array(height)
bmi>23
bmi


array([20.865, 21.643, 22.834, 25.62 ])

In [28]:
x=[1,2,5,15]
import numpy as np
y=np.array(x)
y>2

array([False, False,  True,  True])